import { Migration } from "@mikro-orm/migrations";

export class Migration20260929160704 extends Migration {
  override name = "Migration20260929160704";

  // Old CRC32 codes can't be mapped to sequential IDs, so the table is recreated.
  // Sequence bounds [62^6, 62^7 - 1] guarantee every ID encodes to exactly 7 base62 chars.
  override up(): void | Promise<void> {
    this.addSql(`drop table if exists "short_url" cascade;`);
    this.addSql(
      `create table "short_url" ("id" bigint generated by default as identity (start with 56800235584 minvalue 56800235584 maxvalue 3521614606207) primary key, "long_url" text not null, "created_at" timestamptz not null default now());`
    );
    this.addSql(
      `create index "short_url_long_url_index" on "short_url" using hash ("long_url");`
    );
  }

  override down(): void | Promise<void> {
    this.addSql(`drop table if exists "short_url" cascade;`);
    this.addSql(
      `create table "short_url" ("short_url" varchar(255) not null, "long_url" varchar(255) not null, primary key ("short_url"));`
    );
  }
}
